name: Update results.json

on:
  repository_dispatch:
    types: [update_results]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update results.json
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > payload.json
          node -e "
          const fs = require('fs');
          const payload = require('./payload.json');
          let results = [];
          if (fs.existsSync('results.json')) {
            results = JSON.parse(fs.readFileSync('results.json','utf8'));
          }
          results.push(payload);
          fs.writeFileSync('results.json', JSON.stringify(results,null,2));
          "

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.Yoken }}
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add results.json
          git commit -m 'Update results.json'
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main